version: "3.8"

services:
  it_hub:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      .env
    networks:
      - mynetwork

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data: